### ISSUE TITLE
where can i get the packet srv6_explicit_path_pb2_grpc and srv6_explicit_path_pb2?

### ISSUE THREAD

**Issue by shijy16** [netgroup/srv6-controller#1]
hello, thanks for providing this repo.
 I'm trying to run your grpc api but I can't find these packets: srv6_explicit_path_pb2_grpc and srv6_explicit_path_pb2.
ps: python version 2.7

**Comment by pierventre** [comment]
Hi, you need to generate these files using the proto file - like a typical grpc project.

@cscarpitta

**Comment by shijy16** [comment]
WOW  I had never used proto files before.
Now it works.
Thanks!

**Comment by pierventre** [comment]
Glad you resolved!
